version: "3.8"

services:
  api:
    build: .
    ports:
      - "5001:5000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    expose:
      - "11434"

volumes:
  ollama_data:
